### ISSUE TITLE
Calibrar jacoco para cobertura mínima de 100%

### ISSUE THREAD

**Issue by kyriosdata** [ottoleggio/cs-2019-01#20]
Não há motivo para menos de 100% de cobertura nestes exercícios. Substitua <minimum>0.95</minimum> por <minimum>1</minimum> em seu arquivo pom.xml e, naturalmente, complete o que está faltando.

**Comment by ottoleggio** [comment]
estou tendo problemas de cobertura no arquivo programaExercicio.java

**Comment by kyriosdata** [comment]
Neste tipo de dificuldade a gente aprende. Mas qual tipo? Veja se e viavel
descrever o problema sem eu consultar o codigo. Ficarei aguardando.

Em seg, 27 de mai de 2019 16:54, Octávio Lo Leggio <notifications@github.com>
escreveu:

**Comment by ottoleggio** [comment]
De fato haviam alguns testes a serem feitos, quanto ao problema que mencionei acima, o caio me auxiliou na dúvida. 
Faltava criar um teste "assertNotNull(new Exercicio());"
Obrigado pelo auxilio!

**Comment by kyriosdata** [comment]
Olá Octávio,

se o construtor fosse private, você não veria o Jacoco reclamar da
cobertura.

Fábio
